# Generated by Django 3.1.2 on 2020-10-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200, verbose_name='nome')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data_de_criacao')),
                ('data_de_expiro', models.DateField(blank=True, null=True, verbose_name='data_de_expiro')),
                ('tipo', models.CharField(blank=True, default=' ', max_length=150, null=True, verbose_name='tipo')),
                ('preco', models.PositiveIntegerField(default=10, null=True, verbose_name='preco')),
                ('velho_preco', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='velho_preco')),
                ('i', models.SlugField(blank=True, default='', null=True, verbose_name='i')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='', verbose_name='imagem')),
            ],
        ),
    ]
