# Generated by Django 3.1.2 on 2020-10-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10, null=True, verbose_name='preco'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='velho_preco',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='velho_preco'),
        ),
    ]
