# Generated by Django 3.0.8 on 2020-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0002_auto_20201008_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=200, verbose_name='nome')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data_de_criacao')),
                ('tipo', models.CharField(blank=True, default=' ', max_length=150, null=True, verbose_name='tipo')),
                ('i', models.SlugField(blank=True, default='', verbose_name='i')),
                ('imagem', models.ImageField(blank=True, upload_to='', verbose_name='imagem')),
            ],
        ),
        migrations.DeleteModel(
            name='producto',
        ),
    ]
