# Generated by Django 3.0.8 on 2020-12-04 21:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0003_auto_20201204_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musica',
            name='nome',
        ),
        migrations.AddField(
            model_name='musica',
            name='arquivo',
            field=models.FileField(default=django.utils.timezone.now, upload_to='musics/', verbose_name='arquivo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='musica',
            name='artistas',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='artistas'),
        ),
        migrations.AddField(
            model_name='musica',
            name='sobre',
            field=models.TextField(blank=True, default='A melhor musica de sempre', verbose_name='sobre'),
        ),
        migrations.AddField(
            model_name='musica',
            name='titulo',
            field=models.CharField(default='', max_length=200, verbose_name='titulo'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='i',
            field=models.SlugField(blank=True, default='', verbose_name='iklsdkl'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='tipo',
            field=models.CharField(blank=True, default=' ', max_length=150, verbose_name='tipo'),
        ),
    ]
