# Generated by Django 3.0.8 on 2020-12-04 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0008_auto_20201204_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musica',
            old_name='i',
            new_name='slug',
        ),
        migrations.AddField(
            model_name='cantor',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='iklsdkl'),
        ),
        migrations.AddField(
            model_name='loja',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='iklsdkl'),
        ),
        migrations.AddField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='iklsdkl'),
        ),
    ]
