# Generated by Django 3.0.8 on 2020-12-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0010_auto_20201205_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cantor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='pr_nome',
        ),
        migrations.RemoveField(
            model_name='loja',
            name='ul_nome',
        ),
        migrations.AddField(
            model_name='cantor',
            name='pr_nome',
            field=models.CharField(default='', max_length=200, verbose_name='pr_nome'),
        ),
        migrations.AddField(
            model_name='cantor',
            name='ul_nome',
            field=models.CharField(default='', max_length=200, verbose_name='ul_nome'),
        ),
        migrations.AddField(
            model_name='loja',
            name='nome',
            field=models.CharField(default='', max_length=200, verbose_name='nome'),
        ),
    ]
