# Generated by Django 3.0.8 on 2020-12-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0012_auto_20201205_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantor',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=15, verbose_name='sexo'),
        ),
    ]
