# Generated by Django 3.0.8 on 2020-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0013_cantor_sexo'),
    ]

    operations = [
        migrations.CreateModel(
            name='audio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('byte', models.TextField()),
                ('filename', models.CharField(max_length=300)),
                ('mimetype', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='musica',
            name='audio',
            field=models.FileField(blank=True, upload_to='beatboxapp.audio/byte/filename/mimetype', verbose_name='audio'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='video',
            field=models.FileField(blank=True, upload_to='beatboxapp.video/byte/filename/mimetype', verbose_name='video'),
        ),
    ]
