# Generated by Django 3.0.8 on 2020-12-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0014_auto_20201205_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantor',
            name='password',
            field=models.CharField(default='', max_length=200, verbose_name='password'),
        ),
    ]
