# Generated by Django 3.0.8 on 2020-12-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0015_cantor_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.TextField()),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True)),
                ('para', models.PositiveIntegerField(blank=True, default=0, verbose_name='para')),
            ],
        ),
    ]
