# Generated by Django 3.0.8 on 2020-12-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0016_notificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='ajuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=200)),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data_de_criacao')),
                ('dica', models.TextField()),
                ('slug', models.SlugField(blank=True, default='iklsdkl', verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='notificacao',
            name='slug',
            field=models.SlugField(blank=True, default='', verbose_name='iklsdkl'),
        ),
    ]
