# Generated by Django 3.0.8 on 2020-12-05 20:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0017_auto_20201205_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajuda',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
    ]
