# Generated by Django 3.0.8 on 2020-12-05 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0018_ajuda_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantor',
            name='slug',
            field=models.SlugField(blank=True, default='jkjsuisUIUS8d78sd87as', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='loja',
            name='slug',
            field=models.SlugField(blank=True, default='jdkuuad8a98d98a8uasuuida', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='slug',
            field=models.SlugField(blank=True, default='ksDI89dsdjK', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='slug',
            field=models.SlugField(blank=True, default='hjahjjdhjh', verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, default='jkjkdjsajdkjajasdkjanhdja', verbose_name='iklsdkl'),
        ),
    ]
