# Generated by Django 3.0.8 on 2020-12-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0019_auto_20201205_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='studio',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='email'),
        ),
    ]
