# Generated by Django 3.0.8 on 2020-12-10 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0020_auto_20201205_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.PositiveIntegerField(blank=True, default=0, verbose_name='para')),
                ('sobre', models.TextField()),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data_de_criacao')),
            ],
        ),
    ]
