# Generated by Django 3.0.8 on 2020-12-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0021_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='to',
            field=models.CharField(choices=[('musica', 'musica'), ('cantor', 'cantor'), ('studio', 'studio'), ('loja', 'loja')], default='musica', max_length=200, verbose_name='to'),
        ),
    ]
