# Generated by Django 3.0.8 on 2020-12-12 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0022_denuncia_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='cantor',
            name='confirme_contacto',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='confirme_contacto'),
        ),
        migrations.AddField(
            model_name='cantor',
            name='confirme_email',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='confirme_email'),
        ),
    ]
