# Generated by Django 3.0.8 on 2021-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatboxapp', '0024_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajuda',
            name='slug',
            field=models.SlugField(blank=True, default='iklsdkl', max_length=500, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='mimetype',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cantor',
            name='slug',
            field=models.SlugField(blank=True, default='jkjsuisUIUS8d78sd87as', max_length=500, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='mimetype',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='loja',
            name='slug',
            field=models.SlugField(blank=True, default='jdkuuad8a98d98a8uasuuida', max_length=500, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='musica',
            name='slug',
            field=models.SlugField(blank=True, default='ksDI8lkdlaskldkslkasdlkslsdakl9dsdjK', max_length=500, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='notificacao',
            name='slug',
            field=models.SlugField(blank=True, default='hjahjjdhjh', max_length=500, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='slug',
            field=models.SlugField(blank=True, default='jkjkdjsajdkjajasdkjanhdja', max_length=500, verbose_name='iklsdkl'),
        ),
        migrations.AlterField(
            model_name='video',
            name='mimetype',
            field=models.CharField(max_length=300),
        ),
    ]
